### ISSUE TITLE
Error when trying out

### ISSUE THREAD

**Issue by waldirio** [taftsanders/satellite-leapp-check#10]
Hello @taftsanders 

Let me show this output

```
# python3 satellite_leapp_check.py -v 8.4 -u admin -c content_host_fqdn_here
Enter your Password: 
✅ RHEL 7 version detected
❌ Organization ID 1 is missing Red Hat Enterprise Linux 7 Server RPMs x86_64 7.9
Traceback (most recent call last):
  File "satellite_leapp_check.py", line 443, in <module>
    main()
  File "satellite_leapp_check.py", line 439, in main
```

Is the output above expected? the traceback?

**Comment by taftsanders** [comment]
No, I don't believe that should be expected. From the output it looks like
the Satellite org was missing the RHEL 7.9 repo. Is this how you produced
this error?

**Comment by taftsanders** [comment]
Fixed in commit https://github.com/taftsanders/satellite-leapp-check/commit/2cd75afb982ec77a841a42903285489ebcc01005
