### ISSUE TITLE
When running against satellite itself, it's not supported.

### ISSUE THREAD

**Issue by waldirio** [taftsanders/satellite-leapp-check#30]
When running against satellite itself, it's not supported. Satellite self-registered it's not an option/unsupported.

**Comment by taftsanders** [comment]
Satellite has its own built-in checks and method of upgrading as noted in the documentation. I don't believe it would be a valid use of time to recreate these checks in this script.

If you agree, I can add a statement to the usage section that prints upon running stating this and/or build in a check for the client name == executing server name and exit with this same supportability statement. Let me know your thoughts.

**Comment by waldirio** [comment]
hey @taftsanders 

It looks perfect!

Thank you!
Waldirio
